apiVersion: v1
kind: Service
metadata:
  name: venue-service-svc
  namespace: microservices
spec:
  selector:
    app: venue-service
  ports:
    - protocol: TCP
      port: 3002
      targetPort: 3002
  type: ClusterIP
